name: Compliance

on:
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.h"

jobs:
  compliance_job:
    runs-on: ubuntu-24.04
    name: Run compliance checks on patch series (PR)

    # Skip job if it was triggered by Renovate Bot
    if: ${{ !contains(github.actor, 'renovate') }}

    steps:
      - name: Pip install
        run: |
          pip install unidiff yamllint junitparser python-magic west lxml gitlint

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          path: asset-tracker-template
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Initialize
        working-directory: asset-tracker-template
        run: |
          west init -l .
          west config manifest.project-filter -- \
            "-bsim,-wfa-qt-control-app,-mcuboot,-qcbor,-mbedtls,-oberon-psa-crypto,\
            -nrfxlib,-trusted-firmware-m,-psa-arch-tests,-matter,-cjson,-azure-sdk-for-c,\
            -cirrus,-openthread,-suit-generator,-suit-processor,-cmock,-memfault-firmware-sdk,\
            -canopennode,-chre,-lz4,-nanopb,-tf-m-tests,-zscilib,-cmsis-dsp,-cmsis-nn,-hostap,\
            -liblc3,-loramac-node,-lvgl,-nrf_hw_models,-nrf_wifi,-open-amp,-picolibc,-uoscore-uedhoc,\
            -zcbor,-soc-hwmv1,-coremark,-cmsis,-edtt,-fatfs,-hal_nordic,-hal_st,-hal_wurthelektronik,\
            -libmetal,-littlefs,-mipi-sys-t,-net-tools,-segger,-tinycrypt"
          west update -o=--depth=1 -n

      - name: Run Compliance Tests
        id: compliance
        shell: bash
        env:
          BASE_REF: ${{ github.base_ref }}
        working-directory: asset-tracker-template
        run: |
          export ZEPHYR_BASE="../zephyr"
          $ZEPHYR_BASE/scripts/ci/check_compliance.py \
            -m Codeowners \
            -m Devicetree \
            -m Gitlint \
            -m Identity \
            -m Nits \
            -m pylint \
            -m checkpatch \
            -c origin/${BASE_REF}.. || \
          echo "COMPLIANCE_FAILED=true" >> $GITHUB_ENV

      - name: Process Compliance Results
        working-directory: asset-tracker-template
        shell: bash
        run: |
          # Check for compliance.xml existence
          if [[ ! -s "compliance.xml" ]]; then
            echo "::error::compliance.xml file is missing or empty"
            exit 1
          fi

          # Initialize exit code
          exit_code=0

          # Define error files to check
          error_files=(
            "Nits.txt"
            "checkpatch.txt"
            "Identity.txt"
            "Gitlint.txt"
            "pylint.txt"
            "Devicetree.txt"
            "Kconfig.txt"
            "KconfigBasic.txt"
            "Codeowners.txt"
          )

          # Process each error file
          for file in "${error_files[@]}"; do
            if [[ -s $file ]]; then
              errors=$(cat $file)
              errors="${errors//'%'/'%25'}"
              errors="${errors//$'\n'/'%0A'}"
              errors="${errors//$'\r'/'%0D'}"
              echo "::error file=${file}::$errors"
              exit_code=1
            fi
          done

          # Check if compliance test failed
          if [[ "$COMPLIANCE_FAILED" == "true" ]]; then
            echo "::error::Compliance tests failed. Please check the logs for details."
            exit_code=1
          fi

          exit $exit_code
