name: Target tests

on:
  workflow_dispatch:

jobs:
  target_test:
    name: Target Test
    runs-on:
      label: thingy91x
    steps:
      - name: Display Runner Serial Number
        run: echo "Runner Serial Number is $RUNNER_SERIAL_NUMBER"
