name: AI Code Reviewer

on:
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  code_review:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ai-review'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: DematteisGiacomo/ai-codereviewer@lfsevergnini_playground
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # AI provider
          AI_PROVIDER: "anthropic"
          AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          AI_MODEL: "claude-3-5-sonnet-20241022"
          AI_TEMPERATURE: 0.1

          # Optional configurations
          APPROVE_REVIEWS: true
          MAX_COMMENTS: 10
          PROJECT_CONTEXT: "This is a real-time configurable ultra-low \
                            power capable asset tracking application firmware for the nRF91 Series"
          CONTEXT_FILES: "README.md, docs/ARCHITECTURE.md"
          EXCLUDE_PATTERNS: "**/*.lock,**/*.json,**/*.md"
